FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

EXPOSE 3000
CMD ["./wait-for-it.sh", "db:3306", "--", "node", "app.js"]