FROM node:14

WORKDIR /usr/src/app

# Gabs here - just to ensure we handle the deps - Im not a nodejs dev lolo
COPY package*.json ./
RUN npm install

RUN chmod +x /usr/src/app/wait-for-it.sh

EXPOSE 3000
CMD ["./wait-for-it.sh", "db:3306", "--", "node", "app.js"]
